### ISSUE TITLE
integrity cant be verified

### ISSUE THREAD

**Issue by sirbaconyt** [getappbox/AppBox-iOSAppsWirelessInstallation#263] opened 2024-04-01 21:57 UTC
what certifivates to yall use, because if you didnt already know then integriy cant be verified means the certificate was revoked, so what do yall use? thanksi!

**Comment by vineetchoudhary** [comment] 2024-04-02 03:11
hi @sirbaconyt ,

Did you encounter the error in the AppBox application, or in the iOS application uploaded via AppBox?

**Comment by sirbaconyt** [comment] 2024-04-02 17:41
after installing the app through the link thats what happens on the phone and it doesnt install the app bc the cert is revoked

**Comment by vineetchoudhary** [comment] 2024-04-03 03:30
Hi @sirbaconyt,

When encountering the "the app cannot be installed because its integrity could not be verified" error, there are several possible causes. You can search online for this error and explore different reasons why it might occur.

**Comment by vineetchoudhary** [comment] 2024-04-03 03:32
Closing this issue as a duplicate of #259. Please continue any further communication in #259.

**Closed by vineetchoudhary** 2024-04-03 03:32 UTC
