### ISSUE TITLE
AppBox error - 'crc check failed for file'

### ISSUE THREAD

**Issue by vikas-chandra-mnnit** [getappbox/AppBox-iOSAppsWirelessInstallation#201] opened 2020-09-24 10:19 UTC
After upgrading the macOS to Catalina I have started facing this issue. I am using AppBox version Version 2.9.1 (1).

**Comment by Gahlot** [comment] 2020-09-26 19:35
When try to upload a .ipa made by Xcode(12) getting this error. works fine for .ipa made by XCode(11.3).

**Comment by vineetchoudhary** [comment] 2020-09-28 04:13
@vikas-chandra-mnnit  I'm using AppBox on Catalina since last year and didn't face this issue. @Gahlot ipa file generated by Xcode 12 is also working fine. 

Can you please provide my ipa file in which you are facing this issue? You can also email me on vineetchoudhary[at]live.in

**Comment by vikas-chandra-mnnit** [comment] 2020-09-28 04:25
@vineetchoudhary Thanks for the reply. I am attaching the IPA with this comment. This ipa is generated on Xcode 12. 
[ESP Schedule.ipa.zip](https://github.com/vineetchoudhary/AppBox-iOSAppsWirelessInstallation/files/5289886/ESP.Schedule.ipa.zip)

**Comment by vineetchoudhary** [comment] 2020-09-28 04:45
@vikas-chandra-mnnit I'm able to upload this IPA file without any error. I'm also using AppBox version 2.9.1(1) on macOS Catalina 10.15.7.

https://www.youtube.com/watch?v=1zTmrjjY-ts

**Comment by vikas-chandra-mnnit** [comment] 2020-09-28 04:49
@vineetchoudhary I also using the same version of AppBox and macOS Catalina 10.15.6. Please tell me what other dependency AppBox uses internally that might cause the error.

**Comment by vineetchoudhary** [comment] 2020-09-28 05:04
AppBox internally uses [ZipArchive](https://github.com/ZipArchive/ZipArchive) to extract the IPA file. They are also not able to reproduce this [issue](https://github.com/ZipArchive/ZipArchive/issues/359).

**Comment by kreshikhin** [comment] 2020-10-17 07:20
I met this error too when I used proxy which corrupts some https requests. So checking of proxy or network settings may be helpful for resolving this issue.

**Comment by tkirby** [comment] 2022-03-16 10:20
Getting this error on a few builds lately. Seems like some issue with the zip library. Would be nice if AppBox only unzipped the plist and manifest files it needed and left the rest of the .ipa alone to avoid this issue.

**Comment by tkirby** [comment] 2022-03-17 06:48
I did some more digging on this and I removed the file that AppBox is complaining already exists (in temp directory AppBox is unzipping to) and after rerunning and adding the same .ipa, it worked. Seems like AppBox is extracting to the same place every time and sometimes having it fail due to file already esists.

**Comment by tkirby** [comment] 2022-03-17 07:13
OKay I fixed this by just createding a unique directory in the temp directory to unzip to. So instead of unzip to...

/var/folders/pl/_72l1lfs59n4tqh0nby6zl7c0000gn/T/

AppBox will add a unque directory in the temp dir...

/var/folders/pl/_72l1lfs59n4tqh0nby6zl7c0000gn/T/41A9EF55-B5C5-44D4-B5B6-E4C59BDD0EE8

That way there is no chance of a file collision during unzip.

**Comment by vineetchoudhary** [comment] 2022-05-03 14:29
Fixed in the latest release. https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/releases/latest

**Closed by vineetchoudhary** 2022-05-03 14:29 UTC
